# Generated by Django 4.1.2 on 2022-10-17 12:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Stop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("money", models.DecimalField(decimal_places=2, max_digits=10)),
                ("properties", models.ManyToManyField(to="Stop.property")),
            ],
        ),
    ]
